# Generated by Django 4.2.6 on 2023-10-05 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_title_movie_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='content',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='subject',
            new_name='title',
        ),
    ]
