# Generated by Django 4.2.2 on 2023-10-17 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='like_users',
            field=models.ManyToManyField(related_name='like_todos', to=settings.AUTH_USER_MODEL),
        ),
    ]
