# Generated by Django 4.2.2 on 2023-10-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='check_share',
            field=models.BooleanField(default=False),
        ),
    ]
